version: 2.1
orbs:
  cypress: cypress-io/cypress@1.13.0
workflows:
  build:
    jobs:
      - cypress/run:
          start: 'npm run dev'
          wait-on: 'http-get://localhost:8080'
          record: true
          command: npx cypress run --record --key e5e44a66-f40f-4fa7-97c9-f7942aaafda3
          executor: cypress/browsers-chrome69
          browser: chrome