version: 2.1
orbs:
  cypress: cypress-io/cypress@1.13.0
workflows:
  build:
    jobs:
      - cypress/run:
          start: 'npm run dev'
          wait-on: 'http-get://localhost:8080'
          record: true